# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-01 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('is_super', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': '管理员',
            },
        ),
        migrations.CreateModel(
            name='AdminToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(max_length=16, unique=True, verbose_name='权限')),
            ],
            options={
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16, unique=True, verbose_name='角色')),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.Auth')),
            ],
            options={
                'verbose_name_plural': '角色',
            },
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.Role'),
        ),
    ]
