# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-01 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20191101_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodityattribute',
            name='category',
        ),
        migrations.RemoveField(
            model_name='commodityattribute',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='commoditysubcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Commodity',
        ),
        migrations.DeleteModel(
            name='CommodityAttribute',
        ),
        migrations.DeleteModel(
            name='CommodityCategory',
        ),
        migrations.DeleteModel(
            name='CommoditySubCategory',
        ),
    ]
