# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20191101_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('commodity_img', models.CharField(max_length=255, unique=True)),
                ('brief', models.TextField(verbose_name='商品简介')),
                ('have_discount', models.SmallIntegerField()),
                ('discount', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='商品折扣')),
                ('price', models.PositiveIntegerField(verbose_name='商品价格')),
            ],
            options={
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='CommodityAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=16, verbose_name='产地')),
                ('brand', models.CharField(max_length=16, verbose_name='品牌')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Commodity')),
            ],
            options={
                'verbose_name_plural': '商品属性',
            },
        ),
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'verbose_name_plural': '商品大类',
            },
        ),
        migrations.CreateModel(
            name='CommoditySubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.CommodityCategory')),
            ],
            options={
                'verbose_name_plural': '商品子类',
            },
        ),
        migrations.AddField(
            model_name='commodity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.CommoditySubCategory'),
        ),
    ]
