# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-01 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20191101_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='属性名称')),
                ('val', models.CharField(max_length=64, verbose_name='属性值')),
                ('commodity_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apps.Commodity')),
            ],
            options={
                'verbose_name_plural': '商品自定义属性',
            },
        ),
    ]
