# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-01 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_customattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityDetailImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, unique=True, verbose_name='商品详情图片')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Commodity')),
            ],
        ),
    ]
