# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-02 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20191102_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=16, verbose_name='产地')),
                ('brand', models.CharField(max_length=16, verbose_name='品牌')),
            ],
            options={
                'verbose_name_plural': '商品属性',
            },
        ),
        migrations.CreateModel(
            name='CommodityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(verbose_name='商品详情')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Commodity')),
            ],
            options={
                'verbose_name_plural': '商品详情',
            },
        ),
        migrations.CreateModel(
            name='CommodityDetailImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255, unique=True, verbose_name='商品详情图片')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.CommodityDetail')),
            ],
        ),
        migrations.CreateModel(
            name='CustomAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='属性名称')),
                ('val', models.CharField(max_length=64, verbose_name='属性值')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.CommodityDetail')),
            ],
            options={
                'verbose_name_plural': '商品自定义属性',
            },
        ),
        migrations.AddField(
            model_name='commodityattribute',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.CommodityDetail'),
        ),
    ]
