# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-04 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_auto_20191102_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintoken',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
