# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-04 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_auto_20191104_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintoken',
            name='addtime',
            field=models.BigIntegerField(),
        ),
    ]
